### ISSUE TITLE
mask gff error: list index out of range

### ISSUE THREAD

**Issue by iwangtoknow** [lfaino/LoReAn#11]
Hi Luigi,
Recently I pulled the image tagged `dev_cli`,
a problem raised at the mask step,
here is the log:
``` bash
###RUNNNG REPEATSCOUT AND REPEATMASK TO MASK THE GENOME STARTED AT:	14:07:53 24-12	###
	###RUNNING REPEATSCOUT TO FIND REPETITIVE ELEMENTS###
	###RUNNING REPEATMASKER TO MASK THE GENOME###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 552, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 144, in main
    masked_ref = mseq.repeatsfind(ref_link, wd_split, args.repeat_lenght, threads_use, args.verbose)
  File "/opt/LoReAn/code/manipulateSeq.py", line 252, in repeatsfind
    gff = [y for x in os.walk(working_dir) for y in glob(os.path.join(x[0], name_gff))][0]
IndexError: list index out of range
```
content in `split` folder
``` bash
ls LoReAn_20181224/run/split/
BJCHM5.nuclear.fasta.freq           RM_144740.MonDec241413472018  tmp4_49nifo  tmphshwq69c  tmptx_v8m9j
BJCHM5.nuclear.fasta.repeats.fasta  tmp05pzu06l                   tmph0t2lha5  tmpk5dl_073
```

Thanks
**WANG**

**Comment by lfaino** [comment]
Hi Wang,
can you please try to run the image with the tag latest? additionally, which are you using Singularity or Docker?

Cheers
Luigi

**Comment by iwangtoknow** [comment]
Hi Luigi,
I'm using Docker. I'll try latest.
Thanks!

Happy New Year!

**WANG**

**Comment by iwangtoknow** [comment]
Hi Luigi,
Do you think it is necessary to fill gene id with 0, such as `ID=gene000001` instead `ID=gene1`?
**WANG**

**Comment by lfaino** [comment]
Why do you want to do something like this?

luigi

**Comment by iwangtoknow** [comment]
Hi Luigi,
For example, if you sort the gene name, could have the result like below:
gene1
gene10
gene2
...
gene9

But if you filled into the same length with 0, then it could be this:
gene01
gene02
...
gene10

That's why I have that thought.

**WANG**

**Comment by YuntaoTan** [comment]
you can use {id:0{width}d}.format(id=id,width=width) in python, do this.  just an example, detail you should read python doc.

**Comment by iwangtoknow** [comment]
Thanks

**Comment by ricardo-aaron** [comment]
Hi.
the Verticillium example (/opt/singularity/bin/singularity exec ../../lorean_noIPRS.sif lorean -t 7 --keep_tmp -a -f -d -sr readsChr.subset.fastq -lr longReadsChr8.fastq -pr subset.prot.fasta -sp JR2 -mg chr8.fasta), and in fact any command line that has the -mg option, exits with this error:
### RUNNING IN STRAND MODE AND USING ADAPTER PROVIDED ###
### LOREAN IS CHECKING THAT GMAP IS CORRECTLY BUILD ### 

###GMAP MAPPING  STARTED AT:	00:50:41 08-06	###
###BUILD INDEX###
###MAP###
 ### GMAP IS CORRECTLY BUILD ### 


###RUNNNG REPEATSCOUT AND REPEATMASK TO MASK THE GENOME STARTED AT:	00:50:41 08-06	###
###RUNNING REPEATSCOUT TO FIND REPETITIVE ELEMENTS###
###RUNNING REPEATMASKER TO MASK THE GENOME###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 560, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 149, in main
    masked_ref = mseq.repeatsfind(ref_link, wd_split, args.repeat_lenght, threads_use, args.verbose)
  File "/opt/LoReAn/code/manipulateSeq.py", line 258, in repeatsfind
    gff = [y for x in os.walk(working_dir) for y in glob(os.path.join(x[0], name_gff))][0]
IndexError: list index out of range

**Comment by lfaino** [comment]
@rchavez-langebio ,
I think that you did not follow very well the instruction. You need to download the two files and link the folders to the image as written in the instructions. Repeatmasker  and Augustus need to be able to write to a file and it is not possible in the image.

please folow point 2 and 3 in the installation steps.

Cheers
Luigi
