### ISSUE TITLE
singularity download ERROR

### ISSUE THREAD

**Issue by YuntaoTan** [lfaino/LoReAn#12]
Hi, lfaino
i got following error, /home/tanyt is my home, of course I have permission.
`singularity pull --name mysql.simg shub://ISU-HPC/mysql`
```
$ singularity pull --name mysql.simg shub://ISU-HPC/mysql
ERROR Error downloading https://www.googleapis.com/download/storage/v1/b/singularityhub/o/singularityhub%2Fgithub.com%2FISU-HPC%2Fmysql%2Fb18d7c8ce93ca26133b291d819a273c319f3748f%2F7821837f450e8562d99796f721525c89%2F7821837f450e8562d99796f721525c89.simg?generation=1531946003451686&alt=media. Do you have permission to write to /home/tanyt?
```

**Comment by lfaino** [comment]
Dear @YuntaoTan,
when i read your error, I see that it maybe a problem of bash.  
`Do you have permission to write to /home/tanyt?`

it says that you can not write at the `/home/tanyt` location. 

please have a look if you can create files 

Cheers
Luigi

**Comment by YuntaoTan** [comment]
Dear @lfaino ,
  Thanks for your quike response.
  I try to another machine, the same error
```
tanyt@DESKTOP-036LST1:/mnt/d/bio-soft/mysql$ ll -h
total 0
drwxrwxrwx 1 tanyt tanyt 4.0K Jan 14 17:39 ./
drwxrwxrwx 1 tanyt tanyt 4.0K Jan 14 17:39 ../
tanyt@DESKTOP-036LST1:/mnt/d/bio-soft/mysql$ ../singularity_2.4/bin/singularity pull --name mysql.simg shub://ISU-HPC/mysql
ERROR Error downloading https://www.googleapis.com/download/storage/v1/b/singularityhub/o/singularityhub%2Fgithub.com%2FISU-HPC%2Fmysql%2Fb18d7c8ce93ca26133b291d819a273c319f3748f%2F7821837f450e8562d99796f721525c89%2F7821837f450e8562d99796f721525c89.simg?generation=1531946003451686&alt=media. Do you have permission to write to /mnt/d/bio-soft/mysql?
tanyt@DESKTOP-036LST1:/mnt/d/bio-soft/mysql$ ll
total 0
drwxrwxrwx 1 tanyt tanyt 4096 Jan 14 17:39 ./
drwxrwxrwx 1 tanyt tanyt 4096 Jan 14 17:39 ../
```
I have change the permission to  `777`. the same as. 
I also follow the instruction of https://www.hpc.iastate.edu/guides/containers/mysql-server . download a singularity version2.4.
I try to catch the `Do you have permission to write to /mnt/d/bio-soft/mysql?` for response. but failed.

**Comment by lfaino** [comment]
Hi @YuntaoTan,
i never tested on singularity 2.4. I regularly use 2.6.0.

Can you use that version?

Cheers
Luigi
