### ISSUE TITLE
Problems installing LoReAn

### ISSUE THREAD

**Issue by csijcs** [lfaino/LoReAn#13]
I am trying to install LoReAn on Ubuntu using singularity 2.6.0 accoring to the following bash script:

```
singularity pull --name mysql.simg shub://ISU-HPC/mysql
wget -O ~/.my.cnf https://raw.githubusercontent.com/lfaino/LoReAn/master/third_party/conf_files/my.cnf 
wget -O ~/.mysqlrootpw https://raw.githubusercontent.com/lfaino/LoReAn/master/third_party/conf_files/mysqlrootpw
mkdir -p ${HOME}/mysql/var/lib/mysql ${HOME}/mysql/run/mysqld
singularity instance.start --bind ${HOME} --bind ${HOME}/mysql/var/lib/mysql/:/var/lib/mysql --bind ${HOME}/mysql/run/mysqld:/run/mysqld ./mysql.simg mysql
singularity run instance://mysql
singularity shell --bind ${HOME}/mysql/run/mysqld:/run/mysqld/  docker://lfaino/lorean
cat ~/.bashrc /opt/LoReAn/third_party/conf_files/pathToExport.txt  > ~/.bashrc.lorean
source ~/.bashrc.lorean
cp -r /opt/LoReAn/third_party/software/augustus/ ~/

```
I keep getting the following error:
`ERROR  : Failed to resolve path to /home/csijcs/anaconda2/var/singularity/mnt/container: No such file or directory
ABORT  : Retval = 255
ERROR  : Daemon failed to start
ABORT  : Retval = -1
ERROR: A daemon process is not running with this name: mysql
ABORT: Aborting with RETVAL=255
`
Can you please tell me what I'm going wrong?

**Comment by lfaino** [comment]
Hi,
From what i can see, mysql is not running. Additionally, the path that you reported is a bit strange.

at which step of the installation you get this error?

**Comment by csijcs** [comment]
Basically right in the beginning.  I can't sudo adduser lorean because its a shared server, and I've put the gm_key in my home directory.  Then I run the script above and get the error

**Comment by lfaino** [comment]
to me this path is a bit strange.
"/home/csijcs/anaconda2/var/singularity/mnt/container"

does it exists?

**Comment by csijcs** [comment]
I agree the path is strange and don't know how to change it in the program. Singluarity is actually installed in /home/csijcs/anaconda2/bin. /home/csijcs/anaconda2/var does exist, but noting related to singularity is installed there

**Comment by lfaino** [comment]
I always use the instruction ia this site to install singularity option 1:
https://singularity.lbl.gov/install-linux

**Comment by csijcs** [comment]
I've tried installing through that route and run into problems because I'm not a sudo user. I installed through conda and singularity seems to run find. Is this an issue with singularity or with LoReAn?

**Comment by lfaino** [comment]
i will try to install via conda and see.
i let you know

**Comment by lfaino** [comment]
@csijcs, I did try to install via conda but singularity that conda install is a very old version. 
i already experienced that the 2.4 version of singularity is a problem.

you need to install at least 2.6.
Cheers
Luigi
