### ISSUE TITLE
minimal intron length default

### ISSUE THREAD

**Issue by maleasy** [lfaino/LoReAn#14]
Hi,

I want to use Lorean for annotating a plant genome. I am wondering about the `--max_intron_length` parameter. The default in Lorean is 1000. This seems quite low to me. In gmap, the two corresponding parameters `--max-intronlength-middle` and `--max-intronlength-ends` have defaults of 500000 and 10000. Is there a reason for the low default in Lorean? Should I increase this value, e.g. to the gmap default of 500000?

Thank you!
Best,
Chris

**Comment by lfaino** [comment]
Yes,
we set for fungi which have small introns. you can increase the value as you like

Cheers
Luigi

**Comment by maleasy** [comment]
Thank you!

**Comment by maleasy** [comment]
Dear Luigi,

would it be possible that you share the parameters you used for the rice & arabidopsis annotations in the paper?

Best,
Chris

**Comment by lfaino** [comment]
Are they not in the paper? they should be in a supplementary?
