### ISSUE TITLE
Missing runtime container listed in `INSTALL.md`

### ISSUE THREAD

**Issue by eburgueno** [lfaino/LoReAn#18]
It seems that either [the install instructions](https://github.com/lfaino/LoReAn/blob/master/INSTALL.md#to-start-lorean-after-the-first-use) are out of date, or one of your containers is missing from Docker Hub:

```
# singularity shell --bind ${HOME}/mysql/run/mysqld:/run/mysqld/  docker://lfaino/lorean:iprscan_rpMask
Docker image path: index.docker.io/lfaino/lorean:iprscan_rpMask
ERROR MANIFEST_UNKNOWN: manifest unknown

# singularity pull docker://lfaino/lorean:iprscan_rpMask
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/lfaino/lorean:iprscan_rpMask
ERROR MANIFEST_UNKNOWN: manifest unknown
Cleaning up...
ERROR: pulling container failed!

# docker pull lfaino/lorean:iprscan_rpMask
Error response from daemon: manifest for lfaino/lorean:iprscan_rpMask not found
```

**Comment by lfaino** [comment]
Hi @eburgueno ,
this is an old version that i need to change. I have a new version for yo on the noIPRS branch of github. I`m testing it for few weeks now the noIPRS version and seems to work. Can you check it, please?

here the [link](https://github.com/lfaino/LoReAn/tree/noIPRS)

Cheers
Luigi

**Comment by eburgueno** [comment]
Thanks @lfaino. I'll give the new image a try.
