### ISSUE TITLE
Clarify -u option

### ISSUE THREAD

**Issue by danwiththeplan** [lfaino/LoReAn#2]
Hi, great work, thanks for this software!

```
-u [GFF_file], --update [GFF_file]
```

Can you clarify what this option does? The description is the same as the `-rp` option.

**Comment by lfaino** [comment]
The idea is that you can pass an external gff3 file and this can be used together with the other gff3 files in EVM. I need to check if it is working

**Comment by danwiththeplan** [comment]
OK thanks.
