### ISSUE TITLE
issue with interproscan module

### ISSUE THREAD

**Issue by max-biodatomics** [lfaino/LoReAn#22]
Hi, I tried to run LoReAn with following parameters: 

singularity exec -B /opt/anaconda/envs/lorean/data/config:/opt/LoReAn/third_party/software/augustus/config/ -B /opt/anaconda/envs/lorean/data/Libraries:/usr/local/RepeatMasker/Libraries/ /opt/anaconda/envs/lorean/data/lorean_noIPRS.sif lorean /\
--proteins /home/ubuntu/nvme1/fastq/Clagr3.faa /\
--species  indo1-r1 /\
--fungus /\
--long_reads /home/ubuntu/nvme1/fastq/Indo1-mRNA-2runs-nano.fastq /\
--prefix_gene IN \
--working_dir /home/ubuntu/nvme1/fastq/Indo1-nano-2r-no_mask /\
--threads 32 /\
-v /\
--minimap2 /\
--interproscan /\
/home/ubuntu/nvme1/fastq/Indo1_all-filt.Indo1--4.fna

it failed on the INTERPROSCAN step. Several last messages:

###LOREAN GFF3 STATS###
parsed genome node DAGs: 27059
sequence regions: 1611 (total length: 73345104)
genes: 25447
protein-coding genes: 25447
mRNAs: 25699
protein-coding mRNAs: 25699
exons: 79300
CDSs: 78331
introns: 160794
###INTERPROSCAN ANALYSIS STARTED AT:    13:39:20 06-07  ###
###RUNNING ANALYSIS FOR         25941    mRNA   ###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 560, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 530, in main
    annot, bad_models = iprscan.iprscan(masked_ref, final_update_update, interproscan_out_dir, args.threads)
  File "/opt/LoReAn/code/interproscan.py", line 73, in iprscan
    with open(tsv_file, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/nvme1/fastq/LoReAn_/home/ubuntu/nvme1/fastq/Indo1-nano-2r-no_mask/run_leff669a/interproscan/prot_gffread.mod.uka5hxdr.fasta.tsv'

**Comment by max-biodatomics** [comment]
second attempt with shorter file names gave me: 

### LOREAN GFF3 STATS ###
parsed genome node DAGs: 27140
sequence regions: 1606 (total length: 73352583)
genes: 25533
protein-coding genes: 25533
mRNAs: 25770
protein-coding mRNAs: 25770
exons: 77440
CDSs: 76498
introns: 155001
###INTERPROSCAN ANALYSIS STARTED AT:    03:54:58 07-07  ###
###RUNNING ANALYSIS FOR         25976    mRNA   ###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 560, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 530, in main
    annot, bad_models = iprscan.iprscan(masked_ref, final_update_update, interproscan_out_dir, args.threads)
  File "/opt/LoReAn/code/interproscan.py", line 73, in iprscan
    with open(tsv_file, "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/nvme1/fastq/LoReAn_Indo1-nano-2r-no_mask/run/interproscan/prot_gffread.mod.evhgbfnu.fasta.tsv'


I also found additional details: 
~/nvme1/fastq/LoReAn_Indo1-nano-2r-no_mask/run/interproscan$ cat prot_gffread.mod.evhgbfnu.fastabfa8bgs9.err
/bin/sh: 1: interproscan.sh: not found

looks like the image has issue with file interproscan.sh

**Comment by lfaino** [comment]
Hi @max-biodatomics ,
you are right. I had interproscan in the image but i removed because the image was very big. I`m trying to set it in a different way. Right now it is not working. 

Sorry about it
Luigi

**Comment by max-biodatomics** [comment]
I would say it was obvious. You even call image: noIRPS. 
I copy past instruction without reading. 
By the way, your current instruction in the manual doesn't say to use ":noIRPS" for docker version. Automatically pulled image 8 months old and not working. 
It said: 

> docker run -it --rm -v $PWD:/data lfaino/lorean createUser.py $USER $UID
