### ISSUE TITLE
The created annotation are not correlating to mRNAseq data. 

### ISSUE THREAD

**Issue by max-biodatomics** [lfaino/LoReAn#23]
Hi, 
I have a predicted proteins data from not very close species only and I have nanopore sequencing data. 
The automated annotation with Lorean gave me almost identical to braker2 annotations created with using only protein data. 

I have manually check automatically created annotations for 2 genes. They are not corresponding to mRNA data. The braker2 gives much better results when I used only mRNA data for training.

**Comment by lfaino** [comment]
Hi @max-biodatomics ,
LoReAn includes braker2. The idea of LoReAn is to use better long reads in the sense that if there are reads mapping to the genome in places where there are no gene predicted, LoReAn will try to make a prediction. This mean that a good annotation will not be improved or with little long-reads "RNA" there will be no improvment as well. 
Can you check if you have places in the genome where you have transcription but LoReAn, and BRAKER2, did not pick a gene?
These are the places where LoReAn should work.
Let me know. 

Cheers
Luigi

**Comment by lfaino** [comment]
BTW, which organism are you annotating?

**Comment by max-biodatomics** [comment]
HI @lfaino,
I am annotating some fungi. I used --fungus flag. 
BREAKER2 with --bam LongNanoporeMappedREADS.bam found all regions where is nanopore is mapped. 

We got nanopore data only recently and we used before proteins info with breaker2 for prediction.

Lorean with proteins and nanopore gave us results closer to braker2 with proteins only. 

Manual review of a region with our genes of interest shows that braker2 with nanopore reads gave the best results. It is correctly indicated existing introns but it gave some false positive introns. 

Braker2 with proteins only and Lorean gave multiple mistakes - missing exons, more than half of introns has incorrect boundaries. 

I recently run Lorean with increased weight score for augustus and trinity. I didn't compare results yet.

**Comment by lfaino** [comment]
Hi @max-biodatomics ,
if for you is not a problem, I would like to review the output in order to improve LoReAn performance.
do you think that it is possible?
Cheers
Luigi

**Comment by max-biodatomics** [comment]
I have a business trip coming tomorrow. I will send you some data next week.

**Comment by max-biodatomics** [comment]
I just checked the result with changed weight. I am sure it is not optimal but it gave me results close to braker2 with nanopore sequencing data. There is only minor shifts in introns in some cases. 
I used for trinity 6 and for Augustus 7. 

my guess that you need to increase a default weight for mRNA based calling. In such case if there is mRNA data then it will be used. If there are no, regular prediction.

**Comment by max-biodatomics** [comment]
@lfaino can you give me your email? Preferable gmail. I can share data with you. 
you can send me info to max@biomedican.com

**Comment by max-biodatomics** [comment]
The issue probably can be resolved by changing the default weights. 
As you mentioned that LoReAn should provide better predictions where is no mRNA data. It is good. By increasing weight for evidence-based predicted features will make the quality much higher.
