### ISSUE TITLE
work_dir option doesn't permit clean IO control

### ISSUE THREAD

**Issue by nhartwic** [lfaino/LoReAn#24]
This post both acts hopefully as helpful advice for others using the pipeline and a request that the behavior of LoReAn be changed at some future update.

In order to compute the actual output directory path, Lorean will execute the following command...

```output_dir = os.path.join(root, "LoReAn_" + args.working_dir)```

This makes it very annoying to write lorean output to any location that isn't "$HOME/LoReAn_". In order to control output, I have to use something like the following trick. If I am using singularity for example, I need to use a command that looks like...

```
mkdir ~/LoReAn_bind_points && \
singularity exec \
-B <ACTUAL_PATH_TO_OUTPUT_LOCATION>:~/LoReAn_bind_points \
-B <PATH_TO_AUGUSTUS_CONF_FOLDER>:/opt/LoReAn/third_party/software/augustus/config/ \
-B <PATH_TO_LIBRARY_FOLDER>:/usr/local/RepeatMasker/Libraries/  \
<PATH_TO_LOREAN_IMAGE>/lorean_noIPRS.sif lorean \
-w bind_points ...
```

...If I've built the needed environment myself and have lorean installed, I would need to do something like...

```
ln -s <ACTUAL_PATH_TO_OUTPUT_LOCATION> ~/LoReAn_output && \
lorean -w output ...
```

These commands work but are a bit awkward and basically unreadable unless the developer is already aware that LoReAn mangles the specified work directory by appending it to "$HOME/LoReAn_".

I would prefer it if I could just specify an absolute path as the working directory letting me simply use commands like...

```
lorean -w <ACTUAL_PATH_TO_OUTPUT_LOCATION>
```

I'd recommend changing default behavior to be...
1. If user doesn't specify "-w <OUTPATH>" write output to $HOME/LoReAn_output/
2. if user does specify "-w <OUTPATH>" write output to OUTPATH 

This would noticeably simplify controlling IO for the application.

**Comment by lfaino** [comment]
Dear @nhartwic 
thanks for your suggestion.
however, I think that it is a bit different the behavior.
if you make a dir and you run singularity from the directory, lorean will write the LoReAn_output/ in the directory in which you are in.

I immagine that a user has all files in a directory and  run lorean from that directory and the tool makes a 
 in the folder where all other files are.

does not work like this?
cheers
Luigi

**Comment by nhartwic** [comment]
Looking again, I'm mistaken. I was hasty and made some false interpretations based on behavior observed while using the singularity version of lorean. The commands I gave still seem to be the best way to control output location though.

All things considered, I'd prefer to be able to specify an absolute path and not be forced to use mangled relative paths. At the very least, change the current behavior to 

```
output_dir = os.path.join(root, args.working_dir, "LoReAn_output")
```
doing so would make typical relative path constructs like "../../some/other/location/" function more or less as expected. The following would be even better as it would allow using absolute or relative paths....

```
output_dir = os.path.join(args.workding_dir, "LoReAn_output")
```

If you need output_dir to be an absolute path in order for the pipeline to work, you should be able to use

```
output_dir = os.path.abspath(
    os.path.join(args.workding_dir, "LoReAn_output")
)
```


> I immagine that a user has all files in a directory and run lorean from that directory and the tool makes a in the folder where all other files are.

In general, I don't think this is a good assumption to make, nor is it an assumption that needs to be made. Allowing users to specify absolute paths and name things as they like is a very common feature among command line tools. Allowing users to clearly specify IO makes development and usage in general simpler. If you want default behavior to be to write output to "Lorean_output" or whatever, that is fine, but if a user gives you a path, I think you should use it.

**Comment by lfaino** [comment]
Dear @nhartwic 
i looked into this and I did change the code. however, it is a bit tricky to use it especially if LoReAn is used in combination with Singularity or Docker because the folder set to the new option need to be linked to an host folder with Singularity -B option or docker -v option
in the coming day, i will update the code and the image

Cheers
Luigi

**Comment by lfaino** [comment]
@nhartwic 
i made a change in the tool. Can you test if it works like you need?

Cheers
Luigi

**Comment by nhartwic** [comment]
Sure. Do you have an updated singularity image?

Just followed instructions linked on the main git readme to get a fresh image. That image doesn't have the new --out_dir option so it doesn't seem updated yet. Looking through your code again, I think your update will work. Your docstring should probably be updated though to reflect the fact that out_dir *must* be an absolute path. I'd change "code/arguments.py" line 49 to...

parser.add_argument("-o","--out_dir", nargs="?", default="", help="an absolute path to a location where output should be stored.")

...Is there some specific reason you want to disallow use of relative file paths? The following fits current behavior, as best I can tell, while allowing relative file paths...

```
output_dir = os.path.abspath(
    os.path.join(args.out_dir, "LoReAn" + args.working_dir)
)
```

Sure, relative file paths and stuff are a bit awkward with singularity, but everything is a bit awkward with singularity. Bind points and thinking in terms of the virtual file system are just something singularity users have to get used to.
