### ISSUE TITLE
--long_reads error

### ISSUE THREAD

**Issue by ricardo-aaron** [lfaino/LoReAn#25]
Hi. I'm having this error when using the option --long_reads file.fastq:
###FILTERING OUT LONG READS STARTED AT: 14:14:58 19-07  ###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 560, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 86, in main
    update.upgrade()
  File "/opt/LoReAn/code/update.py", line 131, in upgrade
    a=True)
TypeError: filterLongReads() got an unexpected keyword argument 'a'

**Comment by lfaino** [comment]
Can you sent me the command that you used?

**Comment by ricardo-aaron** [comment]
I have a maker gff3 file that I would like to upgrade and I'm trying this:
/opt/singularity/bin/singularity exec -B /home/rchavez/Langebio/LoReAn/config/:/opt/LoReAn/third_party/software/augustus/config/ -B /home/rchavez/Langebio/LoReAn/Libraries/:/usr/local/RepeatMasker/Libraries/ /home/rchavez/Langebio/LoReAn/lorean_noIPRS.sif lorean --upgrade /home/rchavez/Langebio/dovetail/assembly/gff_final/maker.gff3 --species species_LoReAn --short_reads /home/rchavez/Langebio/spo/fastq/reads_ALL_hisat2.sorted.bam --proteins /home/rchavez/Langebio/genome/annotation/fasta_files/plant_proteins_OSZA_clean.fasta --long_reads /media/rchavez/WD500/pacbio/polished.hq.fastq --mask_genome --working_dir denovo_LtrDetector --max_intron_length 10000 --minimap2 --verbose --threads 24 genome_dna_LtrDetector.fasta
and also tried this as a test, same error:
/opt/singularity/bin/singularity exec -B /home/rchavez/progs_Langebio/augustus/config/:/opt/LoReAn/third_party/software/augustus/config/ -B /home/rchavez/progs_Langebio/RepeatMasker/Libraries/:/usr/local/RepeatMasker/Libraries/ /home/rchavez/Langebio/spo/LoReAn/lorean_noIPRS.sif lorean --threads 7 --species arabidopsis --short_reads hisat2_align.sorted.bam --mask_genome --long_reads SRR3655756_subreads.fastq --upgrade /home/rchavez/Langebio/TAIR/GFF/Araport11_GFF3_genes_transposons.201606.gff --proteins /home/rchavez/Langebio/TAIR/fasta/Araport11_genes.201606.pep.repr.fasta --working_dir tair --verbose --minimap2 /home/rchavez/Langebio/TAIR/genome/TAIR10_Chr_all.fasta

**Comment by lfaino** [comment]
I immagine that. I made some change and i did not test again the update function. I imagine that it is not working. I need to look at it. I need that you know.

**Comment by lfaino** [comment]
@rchavez-langebio 
can you test again? i think that i fix the problem.

Cheers
Luigi

**Comment by ricardo-aaron** [comment]
thanks for the fix. I'll use latest lorean, singularity pull docker://lfaino/lorean:latest, and let you know.

**Comment by ricardo-aaron** [comment]
LoReAn does RepeatScout, RepeatMasker, change names in bam, sam to bam, sorting bam, Trinity, and PASA, and aborts here:
###EVM STARTED AT:      18:40:04 06-08  ###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 596, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 465, in main
    final_evm = grs.genename_evm(args.upgrade, args.verbose, evm_output_dir, dict_ref_name, args.upgrade)
  File "/opt/LoReAn/code/getRightStrand.py", line 523, in genename_evm
    if match[elements[0]]:
KeyError: '##gff-version 3\n'

**Comment by lfaino** [comment]
@rchavez-langebio 
this part of the pipeline is not really stable. I need more test files. can you send me your data in a way that i can test better the pipeline?

Cheers
Luigi
