### ISSUE TITLE
Lorean installation error

### ISSUE THREAD

**Issue by ConcettaDe4** [lfaino/LoReAn#27]
Hi,

I am trying to use lorean.
I have installed the program using the docker, with the command:
`docker run -it --rm -v $PWD:/data lfaino/lorean createUser.py $USER $UID`

After that, I have run lorean on testing data with the command: 

`sudo lorean -a -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq  -lr scaffold3.long.fasta  -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -mg -t 8 --keep_tmp
`
I got this error message: 

```
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 597, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 164, in main
    augustus_species, err_augustus = logistic.augustus_species_func(home)
  File "/opt/LoReAn/code/dirsAndFiles.py", line 182, in augustus_species_func
    path = os.path.join(os.environ["AUGUSTUS_CONFIG_PATH"], "species/")
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'AUGUSTUS_CONFIG_PATH'
```

How can I fix the problem?

Thank you!

Concetta

**Comment by lfaino** [comment]
Dear Concetta,

you can try to install augustus in the host system and after link that augustus conf folder in the host system to the augustus conf folder in the docker image using -v option

`docker run -it --rm -v PATH_TO_AUGUSTUS_CONF_FILE:/opt/LoReAn/third_party/software/augustus/config/ -v $PWD:/data lfaino/lorean createUser.py $USER $UID `

additionally, you do not need to use sudo

I would suggest to use singularity it is much safer than docker

**Comment by ConcettaDe4** [comment]
Hi!
Thank you for your help. I tried to install LoRean with singularity. Using singularity version 2.6.1 I downloaded the image lorean-latest.simg. 
I tried the command on the test data:
```
singularity exec -B
/home/concetta.dequattro/config/:/opt/LoReAn/third_party/software/augustus/config/ -B /home/concetta.dequattro/Libraries/:/usr/local/Repeat
Masker/Libraries/ /home/concetta.dequattro/lorean-latest.simg lorean -a -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq -lr sca
ffold3.long.fasta -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -mg -t 8 --keep_tmp
```
LoRean stopped at the stage prepareEvmInputs and gave me this error: 
```
File "/opt/LoReAn/code/lorean.py", line 597, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 321, in main
    augustus_file, genemark_file = inputEvm.braker_folder_find(braker_folder)
  File "/opt/LoReAn/code/prepareEvmInputs.py", line 115, in braker_folder_find
    gff = [y for x in os.walk(location) for y in glob(os.path.join(x[0], "augustus.hints.gff"))][0]
IndexError: list index out of range
```
When I checked the logs files into braker folder, I saw some error messages in the braker.error.log file.
**Braker.error.log file** : 
```
more braker.error.log
ERROR in file /opt/LoReAn/third_party/software/BRAKER/scripts//braker.pl at line 5806
Failed to execute: perl /opt/LoReAn/third_party/software/gm_et_linux_64/gmes_petap//gmes_petap.pl --verbose --sequence=/home/concetta.dequattro/LOREAN/LoReAn
_Example/Crispa/LoReAn_annotation/run/braker/genome.fa --ET=/home/concetta.dequattro/LOREAN/LoReAn_Example/Crispa/LoReAn_annotation/run/braker/genemark_hints
file.gff --et_score 10 --max_intergenic 50000 --cores=3 --gc_donor 0.001 --fungus 1>/home/concetta.dequattro/LOREAN/LoReAn_Example/Crispa/LoReAn_annotation/r
un/braker/GeneMark-ET.stdout 2>/home/concetta.dequattro/LOREAN/LoReAn_Example/Crispa/LoReAn_annotation/run/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /opt/LoReAn/third_party/software/gm_et_linux_64/gmes_petap//gmes_petap.pl --verbose --sequence=/home/concetta.dequattro/LOREAN/LoReAn
_Example/Crispa/LoReAn_annotation/run/braker/genome.fa --ET=/home/concetta.dequattro/LOREAN/LoReAn_Example/Crispa/LoReAn_annotation/run/braker/genemark_hints
file.gff --et_score 10 --max_intergenic 50000 --cores=3 --gc_donor 0.001 --fungus 1>/home/concetta.dequattro/LOREAN/LoReAn_Example/Crispa/LoReAn_annotation/r
un/braker/GeneMark-ET.stdout 2>/home/concetta.dequattro/LOREAN/LoReAn_Example/Crispa/LoReAn_annotation/run/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!
```
In addition I checked the genemark error file and it gave me this error: 

```
more GeneMark-ET.stderr
Unknown option: gc_donor
```
I have the gm_key in my home and in the folder where I lauched the command singularity.

How can I solve this error?

Thank you!

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
is the key with the dot in front like below?

 ~/.gm_key

**Comment by ConcettaDe4** [comment]
Yes it is. 
In addition, I am working in a HPC cluster.

**Comment by lfaino** [comment]
with an HPC, you need to check where singularity looks for the $HOME directory

you can test (but i never tried) to add a binding option and link the outside $HOME to the inside $HOME

`-B /home/concetta.dequattro/:/home/concetta.dequattro/`

**Comment by lfaino** [comment]
do you use slurm?

**Comment by ConcettaDe4** [comment]
Yes I am using slurm. 
I tested your option but I still have the same error. 

I will contact the administrator of the HPC to understand where the home directory of singularity is located.

**Comment by lfaino** [comment]
I had a similar problem with slurm. I do not remember now how i solved. I should look into it

**Comment by ConcettaDe4** [comment]
OK thank you! 

I have tested LoRean into another server using docker without slurm. 
I download the image in my home directory where there is the geneMark key downloaded from geneMark website (http://exon.gatech.edu/GeneMark/license_download.cgi). 

I ran LoRean and I had the same error message that I already had in the run using singularity.

Could be that the error is not related to the geneMark key?

Why I had the error message into GeneMark-ET.stderr file : Unknown option: gc_donor ? 
I checked the gmes_petap.pl options and I did not see the option gc_donor.  Could be this the real error?

**Comment by lfaino** [comment]
Actually i do not know. 

using docker, the problem is different

let's go bask. you can test the singularity using `singularity shell -B
/home/concetta.dequattro/config/:/opt/LoReAn/third_party/software/augustus/config/ -B /home/concetta.dequattro/Libraries/:/usr/local/Repeat
Masker/Libraries/ /home/concetta.dequattro/lorean-latest.simg`
can you check the value in 
`echo $HOME` in the singularity shell?

**Comment by ConcettaDe4** [comment]
It is /home/concetta.dequattro

**Comment by lfaino** [comment]
can you run genemark from inside the shell of singularity  and see if it works?

**Comment by ConcettaDe4** [comment]
I had run genemark from inside the shell of singularity and it gave me this error 
`Unknown option: gc_donor`

When I remove this option (`--gc_donor`) GeneMark works. So I think that this is the cause of the error. 

How can I remove this options?

Thank you!

**Comment by lfaino** [comment]
So the problem is in braker.pl that is a script not made by me. In fact in braker.pl they use this option. I will test if the new version of braker.pl with the new genemark es solves the issue or I will write to the developer

Cheers
Luigi

**Comment by ConcettaDe4** [comment]
OK thank you for your help.

Cheers,
Concetta

**Comment by ConcettaDe4** [comment]
Hi! 

I was wondering if you have some updates about the solving of the problem in braker.pl.

Thank you!

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
so i did include the newest genemark and i tested braker with it and all worked fine.

can you check if it is the same with you?

Cheers
Luigi

**Comment by ConcettaDe4** [comment]
Hi Luigi,

I tested LoRean pipeline downloading again the docker image.

Now braker worked but I got this error message:

```
##MASKING THE GENOME STARTED AT:       06:45:38 02-12  ###
###STAR MAPPING  STARTED AT:    06:46:22 02-12  ###
###BUILD INDEX###
###MAP###
###SAM to BAM###
###SORTING BAM###
###TRINITY STARTS AT:   06:49:00 02-12  ###
###GMAP MAPPING  STARTED AT:    07:02:21 02-12  ###
###BUILD INDEX###
###MAP###
###PASA STARTS AT:      07:04:02 02-12  ###
###BRAKER1 (USING SHORT READS) AND AAT STARTED AT:      07:10:26 02-12  ###
###RUNNING BRAKER1 ###
100%|##########| 6/6 [00:07<00:00,  1.19s/it]
 73%|#######3  | 130/178 [00:02<00:01, 39.44it/s]
100%|##########| 178/178 [00:03<00:00, 58.73it/s]
###RUNNING EXONERATE ###
Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 597, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 321, in main
    augustus_file, genemark_file = inputEvm.braker_folder_find(braker_folder)
  File "/opt/LoReAn/code/prepareEvmInputs.py", line 115, in braker_folder_find
    gff = [y for x in os.walk(location) for y in glob(os.path.join(x[0], "augustus.hints.gff"))][0]
IndexError: list index out of range
```
In the braker folder I had the augustus.hints.gtf file. 

How can I solve this new error?

Thank you.

Cheers,

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
can you try to download again the image. The problem came from the new update of braker.pl

let me knwo if it works.

cheers
Luigi

**Comment by ConcettaDe4** [comment]
Hi Luigi!

I downloaded again the docker image and I ran lorean on Crispa dataset. 
The script seems to work, I arrived to the final step of the assembly.
I used the following commands:

```
docker run -it --rm -v $PWD:/data lfaino/lorean createUser.py $USER $UID

cd /data/LoReAn_Example/Crispa
nohup lorean -a -rp repeats.scaffold3.bed -sr scaffold3.short_1.fastq,scaffold3.short_2.fastq  -lr scaffold3.long.fasta  -pr scaffold3.prot.fasta -sp crispa scaffold3.fasta -d -f -mg -t 8 --keep_tmp &

```
However when I exit from docker container the pipeline stops. 

How can I launch lorean in background?

Thank you,

Concetta

**Comment by lfaino** [comment]
You can use screen and run docker in a new screen

**Comment by ConcettaDe4** [comment]
Hi! I ran docker in a new screen and it works!

Unfortunately, I got a new error during the last steps of the pipeline.

Here I attached the error:

```
Executing: iAssembler.pl -i seq1_1770037_1777870_359.fasta -h 200  -p 97 -o seq1_1770037_1777870_359.fasta_output  2> seq1_1770037_1777870_359.fasta.log

Executing: iAssembler.pl -i seq1_2164445_2176982_432.fasta -h 200  -p 97 -o seq1_2164445_2176982_432.fasta_output  2> seq1_2164445_2176982_432.fasta.log

Executing: iAssembler.pl -i seq1_998469_1008565_198.fasta -h 200  -p 97 -o seq1_998469_1008565_198.fasta_output  2> seq1_998469_1008565_198.fasta.log

Executing: iAssembler.pl -i seq1_412312_415405_97.fasta -h 200  -p 97 -o seq1_412312_415405_97.fasta_output  2> seq1_412312_415405_97.fasta.log

Executing: iAssembler.pl -i seq1_132585_134254_35.fasta -h 200  -p 97 -o seq1_132585_134254_35.fasta_output  2> seq1_132585_134254_35.fasta.log

Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 597, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 548, in main
    update2 = grs.exonerate(ref_rename, merged_gff3, threads_use, exonerate_wd, args.verbose)
  File "/opt/LoReAn/code/getRightStrand.py", line 303, in exonerate
    for record in SeqIO.parse(prot_file_out, "fasta"):
  File "/usr/local/lib/python3.5/dist-packages/Bio/SeqIO/__init__.py", line 581, in parse
    with as_handle(handle, mode) as fp:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/Bio/File.py", line 88, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/data/LoReAn_Example/Crispa/LoReAn_annotation/run/gmap_output/additional.1.j27bdv4l.gff3.prot.fasta'
```
Thank you,

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
can you try with singularity? I did test the dataset with singularity and it works
let me know if you can otherwise i need to work on it

Luigi

**Comment by ConcettaDe4** [comment]
Hi Luigi,

I tried with singularity and it gave me some errors that is why then I decided to use docker. 
Could you test with docker?

Many thanks,

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
now it should work. however, before running lorean inside docker, you need to run:

`source source /opt/LoReAn/third_party/conf_files/environment`

and after you can run lorean

cheers
Luigi

**Comment by ConcettaDe4** [comment]
Hi!
Sorry for my late reply. I ran again LoRean and now it works!

I have another question: I have several paired end RNA-seq libraries from different conditions.
I gave to LoRean the different libraries separated by comma but when I ran LoRean it seems that it did not consider the short reads RNA-seq libraries. Below you can find the command that I used: 

`lorean -rp repeats.bed -sr cond1_R1_001.fastq.gz,cond1_R2_001.fastq.gz,cond2_R1_001.fastq.gz,cond2_R2_001.fastq.gz,cond3_R1_001.fastq.gz,cond3_R2_001.fastq.gz -pr Creinhardtii_281_v5.6.protein.fa,Osativa_323_v7.0.protein.fa -sp my_species my_genome -d -mg -t 8 --keep_tmp -v`

I was wondering how I should give the different libraries, should I concatenate all the libraries into one library?

Thank you,

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
lorean was not build to work like that. you need to pass only two files: reads_1.fastq and reads_2.fastq. you need to concatenate all file *_1 and *_2 and run again.

sorry for this
Luigi

**Comment by ConcettaDe4** [comment]
Hi Luigi,

Thank you for your answer. I concatenated all RNA-seq data and I ran again LoRean with the following command line:

```
lorean -a adapter.fa -rp repeats_200.bed -sr RNA_R1_001.fastq.gz,RNA_R2_001.fastq.gz -lr pacbio.fasta -pr $Creinhardtii_281_v5.6.protein.fa,Osativa_323_v7.0.protein.fa -sp my_species my_genome.fasta -d -mg -t 8 --keep_tmp -v

```

When I checked the Trinity folder it seems that LoRean used only pacbio reads instead of using short-RNA-seq reads. Here you can find the content of the folder of Trinity:

```
lrwxrwxrwx   1 stefania stefania        148 gen  7 12:01 gmap.long_reads.sam.bam.sorted.bam -> /data/LoRean/LoReAn_annotation/run/gmap_output/gmap.long_reads.sam.bam.sorted.bam
-rw-rw-r--   1 stefania stefania          0 gen  7 12:01 gmap.long_reads.sam.bam.sorted.bam.read_coords.ok
-rw-rw-r--   1 stefania stefania     800123 gen  7 12:01 gmap.long_reads.sam.bam.sorted.bam.read_coords
-rw-rw-r--   1 stefania stefania     800123 gen  7 12:01 gmap.long_reads.sam.bam.sorted.bam.read_coords.sort_by_readname
-rw-rw-r--   1 stefania stefania     800098 gen  7 12:01 gmap.long_reads.sam.bam.sorted.bam.frag_coords
-rw-rw-r--   1 stefania stefania 2328875845 gen  7 12:05 gmap.long_reads.sam.bam.sorted.bam.frag_coverage.wig
-rw-rw-r--   1 stefania stefania          0 gen  7 12:05 gmap.long_reads.sam.bam.sorted.bam.frag_coverage.wig.ok
-rw-rw-r--   1 stefania stefania     402776 gen  7 12:14 gmap.long_reads.sam.bam.sorted.bam.minC1.gff
-rw-rw-r--   1 stefania stefania          0 gen  7 12:14 gmap.long_reads.sam.bam.sorted.bam.minC1.gff.ok
drwxrwxr-x 717 stefania stefania      20480 gen  7 12:14 Dir_gmap.long_reads.sam.bam.sorted.bam.minC1.gff
-rw-rw-r--   1 stefania stefania     852942 gen  7 12:14 Dir_gmap.long_reads.sam.bam.sorted.bam.minC1.gff.listing
-rw-rw-r--   1 stefania stefania          0 gen  7 12:14 Dir_gmap.long_reads.sam.bam.sorted.bam.minC1.gff.ok
-rw-rw-r--   1 stefania stefania          0 gen  7 12:14 partitions.ok
-rw-rw-r--   1 stefania stefania      34200 gen  7 12:14 read_files.list
-rw-rw-r--   1 stefania stefania          0 gen  7 12:14 read_files.list.ok
-rw-rw-r--   1 stefania stefania     155646 gen  7 12:14 trinity_GG.cmds
-rw-rw-r--   1 stefania stefania          0 gen  7 12:14 trinity_GG.cmds.ok
-rw-rw-r--   1 stefania stefania     155646 gen  7 12:20 trinity_GG.cmds.completed
-rw-rw-r--   1 stefania stefania    1788802 gen  7 12:20 Trinity-GG.fasta
-rw-rw-r--   1 stefania stefania      29615 gen  7 12:20 Trinity-GG.fasta.gene_trans_map
-rw-rw-r--   1 stefania stefania      30264 gen  7 12:22 Trinity-GG.fasta.fai
-rw-rw-r--   1 stefania stefania      38677 gen  7 12:36 Trinity-GG.fasta.cidx
```

In addition, the pipeline stopped at braker step. It gave me the following error in the `braker.error.log` :

```
ERROR in file /opt/LoReAn/third_party/software/BRAKER/scripts//braker.pl at line 7711
Failed to execute: /usr/bin/python3 /opt/LoReAn/third_party/software/augustus/scripts/fix_in_frame_stop_codon_genes.py -g /data/LoRean/LoReAn_annotation/run/braker/genome.fa -t /data/LoRean/LoReAn_annotation/run/braker/augustus.hints.gtf -b /data/LoRean/LoReAn_annotation/run/braker/bad_genes.lst -o augustus.hints_fix_ifs_ -s my_species -m off --UTR off --print_utr off -a /opt/LoReAn/third_party/sof
tware/augustus/config/ -C /opt/LoReAn/third_party/software/PASApipeline/bin -A /opt/LoReAn/third_party/software/augustus/config//../bin -S /opt/LoReAn/third_party/software/augustus/config//../scripts -H /
data/LoRean/LoReAn_annotation/run/braker/hintsfile.gff -e /opt/LoReAn/third_party/software/BRAKER/scripts/cfg/rnaseq.cfg  > /data/LoRean/LoReAn_annotation/run/braker/fix_in_frame_stop_codon_genes_augustus.hints.log 2> /data/LoRean/LoReAn_annotation/run/braker/errors/fix_in_frame_stop_codon_genes_augustus.hints.err
```
In addition in the error file `fix_in_frame_stop_codon_genes_augustus.hints.err` I got this error:

```
Traceback (most recent call last):
  File "/opt/LoReAn/third_party/software/augustus/scripts/fix_in_frame_stop_codon_genes.py", line 716, in <module>
    for ifs_line in ifs_handle:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 168: ordinal not in range(128)

```
How can I solve the two errors?

Many thanks for your help! 

Concetta

**Comment by lfaino** [comment]
Hi Concetta,
I see that you use two prot files. can you concatenate them as well?
however, can you share the data? I need to check on the specific dataset to debug the error.

Cheers
Luigi

**Comment by lfaino** [comment]
Hi @ConcettaDe4 ,
can you try LoReAn? I made a new image based on new braker and augustus.
Thanks
Luigi
