### ISSUE TITLE
libopenblas.so.0 cannot open shared object file

### ISSUE THREAD

**Issue by melop** [lfaino/LoReAn#28]
Hello, I installed LoReAn through singularity. There are many errors during the Trinity step, due to missing libopenblas.so.0.

It seems that LoReAn is picking up a faulty numpy installation from my home folder. Should I reset all PYTHONPATH variables before running LoReAn?

Trinity run failed. Must investigate error above.
warning, cmd: /opt/LoReAn/third_party/software/Trinity/util/support_scripts/../../Trinity --single "Dir_gmap.long_reads.sam.bam.sorted.bam.minC1.gff/seq16/2/11203609_11206038.trinity.reads" --output "Dir_gmap.lo
ng_reads.sam.bam.sorted.bam.minC1.gff/seq16/2/11203609_11206038.trinity.reads.out" --CPU 1 --max_memory 3G --seqType fa --trinity_complete --full_cleanup --no_path_merging --max_reads_per_graph 100000   failed w
ith ret: 65280, going to retry.
^Msucceeded(340), failed(2018)   33.6185% completed.    ^Msucceeded(341), failed(2018)   33.6327% completed.    

Error encountered::  <!----
CMD: /opt/LoReAn/third_party/software/Trinity/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py --trinity_fasta /beegfs/group_dv/home/RCui/killifish_genomes/annotation/LoReAn/NFZv2.0/LoReAn_annotation/run
/Trinity/trinity_out_dir/Dir_gmap.long_reads.sam.bam.sorted.bam.minC1.gff/seq3/0/2073479_2247025.trinity.reads.out/Trinity.tmp.fasta.filt --out_prefix /beegfs/group_dv/home/RCui/killifish_genomes/annotation/LoRe
An/NFZv2.0/LoReAn_annotation/run/Trinity/trinity_out_dir/Dir_gmap.long_reads.sam.bam.sorted.bam.minC1.gff/seq3/0/2073479_2247025.trinity.reads.out/Trinity.tmp.fasta.filt.ST --incl_cdna 2>tmp.31990.1580303059.std
err

Errmsg:
Traceback (most recent call last):
  File "/opt/LoReAn/third_party/software/Trinity/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py", line 11, in <module>
    import numpy
  File "/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libopenblas.so.0: cannot open shared object file: No such file or directory

**Comment by lfaino** [comment]
Hi @melop 
i think that you need to try with more memory
cheers
Luigi

**Comment by melop** [comment]
How much RAM would be needed? The node has 256Gb. 
The error seems to be that your script is importing the numpy package from a wrong path ""/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/", which is unexpected because it should instead use your numpy within the singularity image?

**Comment by lfaino** [comment]
Actually you are right... Do you use slurm?

**Comment by melop** [comment]
Yes I'm using SLURM, with a single node with 40 cores and 256Gb of RAM.

**Comment by lfaino** [comment]
I had a similar problem before. you need to load python3 because the code is written in this language and check if you get the error

**Comment by melop** [comment]
I suspect the problem is inside the singularity image. 

If you view /opt/LoReAn/third_party/software/Trinity/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py, at the top you see

#!/usr/bin/env python

However, if you use the singularity command to view /usr/bin/env python --version , like this:
singularity exec -B /LoReAn/config/ -B /LoReAn/Libraries/ lorean_latest.sif  /usr/bin/env python --version
You get: Python 2.7.12

But if I just just execute /usr/bin/env python --version in the host system, it is Python 3.7.4

This means that the default python version inside the singularity image is 2.7.12, which will make Trinity scripts fail. 

In fact, if I force python3 in the singularity command on the Trinity script inside the image, it worked:

singularity exec -B /LoReAn/config/ -B /LoReAn/Libraries/ /LoReAn/lorean_latest.sif  /usr/bin/env **python3**  /opt/LoReAn/third_party/software/Trinity/Analysis/SuperTranscripts/Trinity_gene_splice_modeler.py
usage: Trinity_gene_splice_modeler.py [-h] --trinity_fasta TRINITY_FASTA
                                      [--out_prefix OUT_PREFIX]
                                      [--incl_malign] [--debug] [--verbose]
                                      [--no_squeeze] [--no_refinement]
                                      [--incl_cdna] [--incl_dot]
                                      [--restrict_gene_id RESTRICT_GENE_ID]

**Comment by lfaino** [comment]
I do not think so:
in your first error you get this line;

/beegfs/group_dv/home/RCui/.local/lib/python2.7/site-packages/numpy/init.py

which means that sLURM load python 2 from the system environment and not from singularity


let me do some tests and i will write to you

**Comment by melop** [comment]
Do you know if Trinity requires python3 or python2?
It is still possible that the python2 version within the singularity image is picking up my PYTHONPATH environment and try to load python2 libraries from my home directory.
However, the error goes away if I force python3 within the singularity image to run on the Trinity script. Is there a way to disable any host environment variables when running the singularity image?

**Comment by melop** [comment]
Ok, it looks like Trinity can run with both python 2 and 3. I now fixed the numpy installation in my home directory so the Trinity script seems to run. But it is still strange that it is somehow picking up the numpy in my home directory, which seems unexpected.

**Comment by melop** [comment]
So I fixed the previous problem with:
singularity exec -H ~/virtualized_home --cleanenv
where ~/virtualized_home is just an empty folder.

However now there is a new issue, here is the last lines from the log:

Executing: exonerate --model coding2genome --bestn 1 --refine region --showtargetgff yes --query /beegfs/group_dv/home/RCui/killifish_genomes/annotation/LoReAn/NFZv2.0/LoReAn_annotation/run/exonerate/evm.model.seq7.55_seq7_1284776_1466797.mrna2.prot.fasta --target /beegfs/group_dv/home/RCui/killifish_genomes/annotation/LoReAn/NFZv2.0/LoReAn_annotation/run/exonerateevm.model.seq7.55_seq7_1284776_1466797.mrna2.genome.fasta

Traceback (most recent call last):
  File "/opt/LoReAn/code/lorean.py", line 597, in <module>
    main()
  File "/opt/LoReAn/code/lorean.py", line 589, in main
    temp_dir.cleanup()
UnboundLocalError: local variable 'temp_dir' referenced before assignment

**Comment by lfaino** [comment]
Hi @melop,

can you run the code from the begenning and add --keep_tmp and --verbose

let`s see which error you get
Cheers

**Comment by lfaino** [comment]
@melop 
i made a new image, can you please try to see if the error is gone?

Cheers
Luigi
