### ISSUE TITLE
Error in getRightStrand.py

### ISSUE THREAD

**Issue by stroehleina** [lfaino/LoReAn#35]
Hi Luigi,
I get the following error during the `###GETTING THE STRAND RIGHT` step

`Traceback (most recent call last):`
  `File "/opt/LoReAn/code/lorean.py", line 610, in <module>`
   ` main()`
  `File "/opt/LoReAn/code/lorean.py", line 568, in main`
   ` update3_1 = grs.remove_redudant(ref_rename, update2)`
  `File "/opt/LoReAn/code/getRightStrand.py", line 873, in remove_redudant`
    `fasta = pep_seq(genome, final_evm)`
 ` File "/opt/LoReAn/code/getRightStrand.py", line 774, in pep_seq`
  `  t.start = position[0]`
`IndexError: list index out of range`

I am running this in singularity using the `lfaino/lorean:repetmodeller` image.

`singularity exec -B /home/andreas/LoReAn_runs/TMP:/tmp -B /home/andreas/LoReAn_runs/augustus-config/config:/opt/LoReAn/third_party/software/augustus/config/ -B /home/andreas/LoReAn_runs/RepeatMasker-libs/Libraries:/usr/local/RepeatMasker/Libraries/ /home/andreas/LoReAn_runs/repetmodeller.sif lorean -mm -pr proteins.fasta -sp myspecies -rp repeatmasked.fa.out.gff3 -sr short_reads_R1.fq,short_reads_R2.fq -lr merged_long_reads.fq -m 60000 -q 185000 -n GEN -o MM2NoUpdt -t 20 -v scaffolds.fa`

The last step that ran successfully seems to have been exonerate, although in the log there are a few hundred error messages:

`** FATAL ERROR **: Initial HSP score [-1] less than zero`

Ocassionally I also get this error in the exonerate log:

`Segmentation fault (core dumped)`

However, the log file in which this error occurs is not the one for the last `Executing: exonerate` log printed to STDERR.
These exonerate errors have occurred with other runs that have finished successfully, so I am not sure if they are related to LoReAn crashing.

For STDOUT I get as the last log:

`###GETTING THE STRAND RIGHT     00:39:00 19-08  ###
/home/andreas/MyRun/run/scaffolds.fa.masked.fasta.rename.fasta /home/andreas/MyRun/run/exonerate/exonerate_step4.final.dourjy5j.gff3`

Of two runs with the exact same parameters except a different input genome reference, one finishes, one crashes (on the same machine).

For the failed runs the `exonerate_step4.final.dourjy5j.gff3.gff3` file is empty and the `exonerate_step4.final.dourjy5j.gff3.gff3.gffread.gff3` and `genename_lorean.1.0_tzzpa9.gff3` etc. are not created.

Kind regards,
Andreas

**Comment by AxenArk** [comment]
Hi Andreas,

I came across the same error recently. Seems it is caused by Exonerate reporting both forward and reverse complementary results. I modified line 493 to 499 of getRightStrand.py as below. Hope this workaround will not introduce problems.

    gff = fileGff.readlines()
    flag = 1
    for line in gff:
        if "Query:" in line and "[revcomp]" in line :
            flag = flag * -1
        if "Target:" in line and "[revcomp]" in line :
            flag = flag * -1
        if "# --- END OF GFF DUMP ---" in line:
            break
        if "exonerate:" in line:
            splitLine = line.split("\t")
            #sys.stdout.write (splitLine)
            if (len(splitLine)) > 8:
                #print (flag)
                if flag > 0 :
                    splitLine[6] = "+"
                else :
                    splitLine[6] = "-"                
                chNr = splitLine[0].split(":")


I resumed the pipeline and am waiting for the results.

Best regards,
Hang

**Comment by stroehleina** [comment]
Hi Hang,
thank you so much for this fix!
This solved the problem for me and saved me a lot of headaches.

Best wishes,
Andreas

**Comment by lfaino** [comment]
Dear Both,
thanks for reporting. I applied the fix of @AxenArk and now i`m building a new image. 

cheers
Luigi
