### ISSUE TITLE
Run time

### ISSUE THREAD

**Issue by abayega** [lfaino/LoReAn#4]
Hi,

I am planning to use LoReAn to annotate my new genome. What are the run times like for a genome of ~450Mb?

Also, I wanted to use our Cluster (where I do not have root access). Do you recommend running LoReAn on a standard desktop machine with 16Gb RAM and 8 processors?

Thank you

**Comment by lfaino** [comment]
Hi,
are you going to run LoReAn using Docker?
If you can install Docker, i think that it may work on the Cluster. However, i think that you need to talk to your system administrator.
 I wrote the code with the intention of running it on a standard desktop. I have a similar machine to the one that you described (16Gb and 8 threads) and it may take some time. A similar genome without long reads takes about 1 day on a 32 threads computer.

If you want to run, please contact me again. I have an improved version of the tool and I can tell you how to run it. In the new version I added interproscan.

Cheers
Luigi

**Comment by abayega** [comment]
I really want to try LoreAn. We have both long and short reads and we have just assembled the genome. This seems like a perfect fit for LoReAn. Therefore, kindly share with me the new version (and hopefully this can be referenced when we publish this work). I will probably install the docker on my machine (let me email our cluster admin to see if they can install docker for me).

**Comment by lfaino** [comment]
ok. let me know when you are ready and I will write you how to use the new "beta" docker image

BTW. i`m working on a plant genome of the same size more or less. I suggest you to mask the genome and after use LoReAn on the masked genome. We can discuss this as well

Cheers
Luigi
