### ISSUE TITLE
annotation update failed, PASA error.

### ISSUE THREAD

**Issue by iwangtoknow** [lfaino/LoReAn#5]
Dear Luigi,
       I have met a issue when I use your latest docker image, actually it's the issue mit pasapipeline, I opened a issue in pasa git, but I still don't know how to solve this, do you have any advice?
  `https://github.com/PASApipeline/PASApipeline/issues/78`

Thanks for your rely.

**Comment by lfaino** [comment]
Dear Ivan,
i saw that PASA changes. version in the last few weeks. I will make a new image and i will check if the error is fix.

I let you know.

Luigi

**Comment by iwangtoknow** [comment]
Thanks Luigi,
smile
WANG Yingqing

**Comment by iwangtoknow** [comment]
Thanks Luigi,
Smile
WANG Yiqing

**Comment by lfaino** [comment]
Hi Wang,
can you test this image? it is development image that includes iprscan. i tested an it  should work.
you can run like this

`docker run -it --rm -v $PWD:/data lfaino/lorean:iprscan_rpMask createUser.py $USER $UID
`

Cheers
Luigi

**Comment by iwangtoknow** [comment]
Thanks Luigi!

**Comment by lfaino** [comment]
HI Wang,
did it work? can we close the issue?

Cheers

**Comment by iwangtoknow** [comment]
Dear Luigi,
Yes, I just checked. The process is still running, it has entered the interproscan step.
Thanks.
