### ISSUE TITLE
Multiple adapter

### ISSUE THREAD

**Issue by palfalvi** [lfaino/LoReAn#6]
Hi @lfaino ,

First of all, thank you for the great pipeline. I would like to install LoReAn in a few days, when our system maintenance is finished and try on our plant genome (~2Gb, with lots of illumina, PacBio and ONT RNA-seq data).

If I understood well, LoReAn will orientate the long reads based on the adapters i feed to it. My question is that, can it work with several adaptors? I have 16 PB cells and 4 ONT FC with same adaptors (SMRTer oligo), and one ONT FC with custom primers. Can I just feed them all the oligos and it will select the best hit or will it cause some problem (e.g. highly extended run time)? 

Thanks for your answer in advance!

**Comment by lfaino** [comment]
Hi,
well the way that i configure the adapter analysis should not support multiple adapter. however, i`m working on an improvement. I can come back to you when this is ready. it should take few days and you can help me in testing it.

Cheers
Luigi

**Comment by palfalvi** [comment]
Hi Luigi,

Thanks, sounds great! I am happy if I can help testing or anything!

Best,
Gergo

**Comment by lfaino** [comment]
Hi Gergo,
i tried to make the multiple adapter work, but i was not able.

sorry
Luigi

**Comment by palfalvi** [comment]
Hi Luigi,

Thank you for your effort. 

Do you think in that case it can work if I clip specific adaptors and go with polyA only? Maybe not that accurate, but could improve. What is your opinion?

Best,
Gergo

**Comment by lfaino** [comment]
Hi Gergo,
I made an automatic way of discovering adapters based on:
1) low GC content assuming that the adapter contain part of the poly A
2) this sequence should be highly represented in the reads.

you can run lorean with -a option and see what happens

give a try and please let me know the result

Cheers
Luigi
