### ISSUE TITLE
Minimal contig limitation?

### ISSUE THREAD

**Issue by iwangtoknow** [lfaino/LoReAn#7]
Hi Luigi,
I annotated my assembly with 23 contigs, but only the biggest 8 contigs has gene models, other contigs include the mitocondria contig have no gene predicted results. Is there a minimal contig length limitation? And can I set a custom number?

---
I try to only annotate the mito chromosome but genome mask error occured, after I remove the `-mk` option, genemark error occured and I found `--min_contig 50000` in `gmes.log`, but the mito chromosome length is 33K+. Maybe that's what I'm asking about.

Thanks.
WANG Yiqing

**Comment by lfaino** [comment]
mmmm.
This is the first time that i see this option. Can you check if the contigs have predictions in the augustus folder and in the gmes folder?
Cheers
Luigi

**Comment by lfaino** [comment]
As I suspected:
"50000 (default); will ignore contigs shorter then min_contig in training"

this is from GeneMarks

the problem is somewhere else.

**Comment by iwangtoknow** [comment]
I'll check the file you mentioned.
BTW: your avatar is handsome.

**Comment by iwangtoknow** [comment]
Hi Luigi,
I checked the files, I'm wrong, not the limited in minimum contig length, but two specific contigs.
![no_result1](https://user-images.githubusercontent.com/35318350/41263951-a8bb1f12-6e1c-11e8-9f8f-84f5240d9077.png)
![no_result2](https://user-images.githubusercontent.com/35318350/41263953-ad76dc26-6e1c-11e8-9e3d-5709a61e58df.png)

---

Another question, because of the different nature between nuclear and mitocondria genome, is it necessary separate the mito-chromosome to annotate?

WANG Yiqing

**Comment by lfaino** [comment]
To be honest, I do not know if you need to annotate in a different way. I would suggest to check if any reads are mapped on these contigs. 
If there are reads, you can think that you have genes expressed and you should be able to annotate them. If no reads, maybe there are no genes to annotate.

sorry I can not help you on this.

Cheers
Luigi

**Comment by iwangtoknow** [comment]
Thanks Luigi.

2018-06-12 18:51 GMT+08:00 Luigi Faino <notifications@github.com>:
