### ISSUE TITLE
Non-docker installation possible?

### ISSUE THREAD

**Issue by yo54233154** [lfaino/LoReAn#8]
Hi, I'd like to know if it is possible to install LoReAn without docker? I think we have most of the required softwares installed , though some might not match the specific version listed. 
For some reasons, we simply don't have docker installed and don't want to go through that much trouble.
I guess I can just edit the python scripts and point them to where our softwares are installed , correct ?

Thank you.

**Comment by lfaino** [comment]
Hi,
it is possible. I have done in the past for testing purpose. It is not necessary to change the software locations. You can edit the [https://github.com/lfaino/LoReAn/blob/master/third_party/conf_files/pathToExport.txt](url) to match your path and add to the .bashrc. after source the .bashrc and you are done.

However, I can ensure you that docker installation is very easy (if your system admin allows to use it). I think that only 4 lines of commands are required. Moreover, PASA installation would take quite some time. 
I strongly suggest to use docker.
I would suggest to use a new version of LoReAn at the dev branch. It is more accurate and fast.
if you decide to use docker, you can download the new version using:
`docker run -it --rm -v $PWD:/data lfaino/lorean:iprscan_rpMask createUser.py $USER $UID`

Cheers

**Comment by lfaino** [comment]
Hi,
I just made a new release of LoReAn. I made some changes and now it can work without root access. 
I made it work with SINGULARITY software (v2.6.0) which is a tool similar to docker but does not require root access. You can test if it works following the information at the [dev branch of LoReAn](https://github.com/lfaino/LoReAn/blob/dev/INSTALL.md).

It should work but it is in development. Let me know if you want to test and if it works

Cheers
Luigi

**Comment by doctorbird** [comment]
Very interested in the Singularity install, any caveats before I give it a try on our cluster?

**Comment by lfaino** [comment]
Honestly, no idea. I did not try because i do not have access to a cluster right now. If you succeed, please let me know
